version: '3'

tasks:
    check:
        cmds:
            - echo "Comprobando sintaxis..."
            - gofmt -e {{.TASKFILE_DIR}}/...

    test:
        cmds:
            - echo "Realizando tests..."
            - go test {{.TASKFILE_DIR}}/...